server:
  port: 8080
springdoc:
  swagger-ui:
    path: /v1/test/index.html
    diff:
      latest-doc-path: upload_folder
      enabled: true
      path-web: /changelog
  api-docs:
    path: /v1/test/api-docs
