server:
  port: 8080
springdoc:
  swagger-ui:
    path: /v1/test/index.html
    diff:
      latest-doc-path: upload_folder
      enabled: true
      path-web: /changelog
      telegram:
        api-key: 5300827301:AAEaytUiaPBPQw2SH5n2dI0HDmsxZrVqm9s
        web-hook: https://d837-213-230-87-197.eu.ngrok.io
        chat-id: -1001748422666

  api-docs:
    path: /v1/test/api-docs
